### ISSUE TITLE
Missing dependency for dev-python/packaging

### ISSUE THREAD

**Issue by Quarky9** [ZeroPointEnergy/gentoo-pyfa-overlay#1]
pyfa v2.9.4
EVE Data Version: 1514398 (2019-05-28 14:07:48)

OS version: Linux-5.1.7-gentoo-x86_64-AMD_FX-tm-8150_Eight-Core_Processor-with-gentoo-2.6
Python version: 3.6.5 (default, Jun  8 2019, 12:34:14) 
[GCC 8.3.0]
wxPython version: 4.0.6 (wxWidgets 3.0.4)
SQLAlchemy version: 1.3.3
Logbook version: 1.1.0
Requests version: 2.21.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/pyfa", line 133, in <module>
    from gui.mainFrame import MainFrame
  File "/usr/lib64/python3.6/site-packages/pyfa/gui/mainFrame.py", line 72, in <module>
    from service.update import Update
  File "/usr/lib64/python3.6/site-packages/pyfa/service/update.py", line 28, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'

**Comment by ZeroPointEnergy** [comment]
Whoops, was already installed on my system and I thought that's just a development dependency. Fixed in 2dfd21ed44330c99400410fdfb11c34fd1d7fa16 . Thanks for reporting.
