### ISSUE TITLE
License is all-rights, while source is gplv3

### ISSUE THREAD

**Issue by liamdennehy** [ZeroPointEnergy/gentoo-pyfa-overlay#2]
Why is pyfa licensed propriatery when the [source](https://github.com/pyfa-org/Pyfa/blob/master/LICENSE) is GPL?

**Comment by ZeroPointEnergy** [comment]
Hello @liamdennehy 

While the Pyfa source is indeed GPLv3, there are images and data files distributed with the program that are property of CCP and not under an open source license.

Here is the discussion we had with upstream and a gentoo developer from the license team:
- https://github.com/gentoo/gentoo/pull/7367#discussion_r186260729
- https://github.com/pyfa-org/Pyfa/issues/1505

**Comment by liamdennehy** [comment]
So you have the license holder's permission to redistribute?

**Comment by ZeroPointEnergy** [comment]
The Pyfa project has the permission to redistribute those files. But it is not clear if this translates to Gentoo (or any other distribution) being able to redistribute it. CCP was extremely vague about this and never gave a clear answer.

To be save we also added `RESTRICT="mirror bindist"`, which means we do not redistribute the Pyfa sources with the non-free images and data files. The ebuild will instead always directly get the tarball from Github.

Also the license in the ebuild mentions both licenses: `LICENSE="GPL-3+ all-rights-reserved"`

**Comment by ZeroPointEnergy** [comment]
I will close this now. Feel free to reopen if something is still unclear.
